name: CI

on: [push]

jobs:
  secrets-analysis:
    runs-on: ubuntu-20.04
    steps:
      - name: Check secrets
      - run: docker run --rm -v "$(pwd):/proj" dxa4481/trufflehog --regex --entropy=False --max_depth=1 file:///proj

  static-analysis:
    runs-on: ubuntu-20.04
    steps:
    - name: Scanning dependencies
      run: npm audit
    - name: SAST njsscan
      uses: ajinabraham/njsscan-action@master
      with:
        args: './src'

  build:
    runs-on: ubuntu-20.04
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Installing dependencies
        run: npm install

      - name: Executing tests
        run: npm test
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432 # ${{ job.services.postgres.ports[5432] }}
      
      # - name: Set up Docker Build
      #   uses: docker/setup-buildx-action@v1
      #   with:
      # install: true
      - uses: docker/build-push-action@v2
        with:
          tags: localbuild/bestreads-backend:latest
          push: false

      - name: Run container image
        uses: addnab/docker-run-action@v3
        with:
          image: localbuild/bestreads-backend:latest
          # docker build . -t localbuild/bestreads-backend:latest
          # docker run -e NODE_ENV=docker -e POSTGRES_HOST=postgres -d localbuild/bestreads-backend:latest -p 3000:3000

      - name: Container Scanning
        uses: hands-lab/dockle-action@v1
        with:
          image: 'localbuild/bestreads-backend:latest'
          exit-code: '1'
          exit-level: FATAL

      - name: DAST OWASP Scanning
        uses: zaproxy/action-baseline@v0.4.0
        with:
          target: http://localhost:3000
